universe = vanilla
#+DESIRED_Sites="T2_US_UCSD"
+ProjectName="cms.org.cern"

request_cpus = 1
#request_disk = 8000000
#request_memory = 1024

Notification = Never
Log=logs/log_produce_mc_$(Cluster).$(Process).log
output=logs/log_produce_mc_$(Cluster).$(Process).out
error=logs/log_produce_mc_$(Cluster).$(Process).err

Requirements = HasSingularity
#Requirements = (TARGET.Machine == "cms11.physics.ucsb.edu")
#Requirements = (TARGET.Machine == "cms18.physics.ucsb.edu")
+SingularityImage = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el7:x86_64"

transfer_executable = True
transfer_input_files = voms_proxy.txt,config/SMS-TChiHH_HToGG_2D_TuneCP5_13TeV-madgraphMLM-pythia8__RunIISummer20UL16.FullSim.env,config/SMS-TChiHH_HToGG_2D_TuneCP5_13TeV-madgraphMLM-pythia8__RunIISummer20UL16__fragment.py
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

## Testing condor
#executable = check_env.sh
#queue

# Testing small (Takes 1.5 hours)
executable = produce_mc_RunIISummer20UL16.SUS.seed.sh
RND_SEED = $(Process) + 0
arguments = $INT(RND_SEED) 200 SMS-TChiHH_HToGG_2D_TuneCP5_13TeV-madgraphMLM-pythia8__RunIISummer20UL16.FullSim.env
queue 1

## Testing larger (Takes 5 hours)
#executable = produce_mc_RunIISummer20UL16.SUS.seed.sh
#RND_SEED = $(Process) + 0
#arguments = $INT(RND_SEED) 1000 SMS-TChiHH_HToGG_2D_TuneCP5_13TeV-madgraphMLM-pythia8__RunIISummer20UL16.FullSim.env
#queue 10

## Run 1 (10k could take 14 hours)
#executable = produce_mc_RunIISummer20UL16.SUS.seed.sh
#RND_SEED = $(Process) + 0
#arguments = $INT(RND_SEED) 3000 SMS-TChiHH_HToGG_2D_TuneCP5_13TeV-madgraphMLM-pythia8__RunIISummer20UL16.FullSim.env
#queue 300
